export const taskTypes = [
  "New Business Pack",
  "Additional Contribution Pack",
  "Change of Address",
  "Change of Premiums",
  "Change of Method of Payment",
  "Beneficiary Nomination",
  "Policy Reinstatement",
  "Premium Holiday",
  "Surrender",
  "Withdrawal",
  "Illustration",
  "Valuation",
  "Fund Switch",
  "Arrears",
  "Transfer of Agency",
  "FE Analytics Request",
  "Review Pack Request",
  "Paid Up Instruction",
];